### ISSUE TITLE
Aggiungere asciidoc all'immagine

### ISSUE THREAD

**Issue by VaiTon** [csunibo/build-image#1]
Da https://github.com/csunibo/config/issues/65

**Comment by lucat1** [comment]
Come siamo messi su questa issue poi?

**Comment by VaiTon** [comment]
Aggiunto!

**Comment by VaiTon** [comment]
Prima aggiunta in https://github.com/csunibo/build-image/commit/3d7971097f25d567e6a75e3951b3731930a964b9
