### ISSUE TITLE
Typst

### ISSUE THREAD

**Issue by foxyseta** [csunibo/build-image#7]
Aggiungerei `typst` ai pacchetti per permettere la compilazione di sorgente Typst in PDF. @lucat1 e io siamo utenti soddisfatti, ed è già stata aperta una PR in Typst https://github.com/csunibo/ipim-ingegneria-del-software/pull/15 in passato. Typst è in Beta dal 21 Marzo 2023 (https://typst.app/docs/community/), e riscuote un certo interesse.

Su Alpine linux, tuttavia, al momento è ancora in Edge: https://pkgs.alpinelinux.org/package/edge/community/x86_64/typst, quindi per favore le cose come si deve dovremmo aspettare l'uscita ufficiale di Alpine 3.20 e solo allora aggiungerlo. Cosa ne dite @csunibo/esperti-ci-cd?

**Comment by samuelemusiani** [comment]
Sinceramente non ho provato, però volendo si può già mettere come supporto sperimentale anche se è in Edge. Anche perché non so quanto ci voglia prima che diventi stabile

**Comment by samuelemusiani** [comment]
Oltretutto ho visto adesso che esisteva questa: https://github.com/csunibo/build-image/tree/typst

**Comment by lucat1** [comment]
Si penso richieda molto poco effort. Per quanto lo considerano in beta è molto usabile se non si cerca la cosa più raffinata al mondo tipograficamente. Sicuramente è meno stroke-inducing di latex.

**Comment by foxyseta** [comment]
> Oltretutto ho visto adesso che esisteva questa: https://github.com/csunibo/build-image/tree/typst

Ottimo occhio! La cancellerei e aspetterei Alpine 3.20 giusto perché:
- edge in produzione mi sembra troppo sciatto usarlo e sono proprio line docker in più
- tecnicamente alpine 3.20 è uscito silenzionamente ieri (gli endpoint dei vari mirror sono già online), solo che l'ha pubblicizzato sui social media in via ufficiosa e devono ancora aggiornare il sito.

Lavoro io su una branch nuova allora a breve. Con la 3.20.
