### ISSUE TITLE
Gestione di file con spazi

### ISSUE THREAD

**Issue by foxyseta** [csunibo/build-image#9]
Anche se tutte le nostre regexp vietano l'uso degli spazi vuoti, ci sono file i cui nomi [volutamente non controlliamo](https://csunibo.students.cs.unibo.it/wiki/raccolte-di-risorse/controlli-automatici/). In linea di principio questi possono contenere spazi vuoti, e dobbiamo quindi assicurarci che vengano convertiti comunque con successo. Questo non è al momento il caso. Esempio:
https://github.com/csunibo/informatica-teorica/pull/5 (In questo caso particolare i file non erano esenti dal controllo dei nomi, che giustamente fallisce, ma il problema si sarebbe presentato lo stesso se anche lo fossero stati. Inoltre è bene che i risultati dei vari controlli siano indipendenti.)

Ci sono diversi punti nei nostri script Bash in cui non mettiamo le virgolette attorno a espansioni di variabili che rappresentano i nomi dei file (forse qualcosa come https://github.com/csunibo/update/blob/main/.github/workflows/shellCheck.yml farebbe comodo). Inoltre in `rec` mi pare iteriamo sull'output di `find` con un ciclo Bash `for`, il che probabilmente interpeta nomi di file con spazi come iterazioni multiple.

@csunibo/esperti-ci-cd confermate?

**Comment by samuelemusiani** [comment]
Confermo che gli spazi per ora non li consideriamo. Bash e gli spazi non vanno particolarmente d'accordo, quindi io sarei per evitare completamente di includere file nelle repository con spazi nel nome.

Se volete comunque ho fatto un pr (#10) con qualche modifica in modo che almeno questa repo sia compatibile con gli spazi. Andrebbero però provati tutti i tools, soprattutto statik

**Comment by samuelemusiani** [comment]
Confermo che per ora statik non funziona con file che hanno spazi nel nome

**Comment by samuelemusiani** [comment]
Ho fatto funzionare statik https://github.com/csunibo/statik/pull/14

**Comment by foxyseta** [comment]
> Confermo che gli spazi per ora non li consideriamo. Bash e gli spazi non vanno particolarmente d'accordo, quindi io sarei per evitare completamente di includere file nelle repository con spazi nel nome.

mi sembrava un po' eccessivo limitare i nomi dei filensolo per limitazioni della shell ecco tutto.  Al momento permettiamo nomi arbitrari perché le risorse dei prof possono avere nomi arbitrari e talvolta ha senso preservarli

> Ho fatto funzionare statik [csunibo/statik#14](https://github.com/csunibo/statik/pull/14)

Toppp. Quindi il resto delle modifiche basta farle su questa repo giusto? Config mi sembrava a posto a una prima occhiata.

**Comment by samuelemusiani** [comment]
Teoricamente basta mergiare #10 e dovrebbe funzionare tutto se non mi sono dimenticato di qualcosa di importante. L'unica cosa che non so è lato dynamik se funzionerà tutto @ali-benny

**Comment by ali-benny** [comment]
> L'unica cosa che non so è lato dynamik se funzionerà tutto @ali-benny

Bella domanda, in teoria non dovrebbe cambiare nulla, vedremo se si rompe tutto :D

**Comment by samuelemusiani** [comment]
#10
